[build]
  command = "npm run generate"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "static"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"

# Mailchimp archive redirect
[[redirects]]
  from = "/archive"
  to = "/community/newsletter"
  status = 301
