// Generates public/_redirects (Netlify) for the legacy URLs of the bodies of work that now exist on this site, from the stage 1 and 6
// data. Rulings of 6 October 2026: graduate programs, water data portals and the document library are built; the two faculty/student
// resource bodies are covered by /learn-train. Bodies ruled "drop" (guest lecturers, instrumentation facilities, broken URLs, the short
// links /apply/watersofthack and /register/open-house, /lets-talk-about-water) get no redirect: they return 404 on purpose.
// Not yet ruled, so not redirected here: the 10 other library documents, the Summer Institute reports, the Water Science Exchange.
// Every legacy PDF that is hosted here redirects to its hosted copy, from the provenance table agent/parity/documents-sources.csv.
// Run from the repository root: node scripts/parity/redirects.mjs   (add --check to compare the committed file with a fresh run; verify.sh does)
import fs from 'node:fs'
const csv = f => {
  const [head, ...rows] = fs.readFileSync(f, 'utf8').trim().split('\n')
  const keys = head.split(',')
  return rows.map(r => {
    const cells = []; let cur = '', q = false
    for (const ch of r) { if (ch === '"') q = !q; else if (ch === ',' && !q) { cells.push(cur); cur = '' } else cur += ch }
    cells.push(cur)
    return Object.fromEntries(keys.map((k, i) => [k, cells[i] ?? '']))
  })
}
const path = u => new URL(u).pathname.replace(/\/+$/, '') || '/'
const rules = new Map() // source path -> [target, reason]
const add = (from, to, why) => { if (rules.has(from) && rules.get(from)[0] !== to) throw new Error(`two targets for ${from}`); rules.set(from, [to, why]) }
const bodies = csv('agent/parity/url-bodies.csv')
const TO = {
  'Graduate programs directory': ['/learn-train/graduate-programs', 'graduate programs: one table'],
  'Water data portals catalog': ['/data-platforms/portals', 'water data portals: one table'],
  'Document library': ['/about/documents', 'document library pages: the documents page'],
  'Faculty resources': ['/learn-train', 'faculty resources: covered by Learn & Train'],
  'Student resources': ['/learn-train', 'student resources: covered by Learn & Train'],
}
// Library pages for documents that are not hosted here yet and not yet ruled on: the Summer Institute reports (to be published later
// as HydroShare resources) and the 10 other documents. They get no redirect until Jordan rules (see the 6 October status page).
const HELD = new Set([
  'national-water-center-innovators-program-summer-institute-report-2016', 'national-water-center-innovators-program-summer-institute-report-2017',
  'national-water-center-innovators-program-summer-institute-report-2018', 'national-water-center-innovators-program-summer-institute-report-2019',
  'national-water-center-innovators-program-summer-institute-report-2022', 'national-water-center-innovators-program-summer-institute-report-2023',
  'national-water-center-innovators-program-summer-institute-report-2024', 'water-prediction-innovators-program-summer-institute-report-2025',
  'water-prediction-innovators-summer-institute-report-2026',
  '2018-membership-meeting-test', 'a-message-from-cuahsis-executive-director', 'a-national-center-for-hydrologic-synthesis-scientific-objectives-structure-and-implementation',
  'a-vision-for-hydrologic-science-research', 'cuahsi-hydrologic-information-systems', 'designing-hydrologic-observatories-a-paper-prototype-of-the-neuse-watershed',
  'designing-hydrologic-observatories-as-a-community-service', 'facilities-for-transforming-hydrological-science', 'hydrologic-observatory-network',
  'statement-on-holistic-evaluation-of-research-in-hydrologic-sciences', 'the-cuahsi-hydrological-measurement-facility-community-survey-2005',
])
let held = 0
const counts = {}
for (const b of bodies) {
  const t = TO[b.body]; if (!t) continue
  if (b.body === 'Document library' && HELD.has(path(b.legacy_url).split('/').pop())) { held++; continue }
  const p = path(b.legacy_url)
  add(p, t[0], t[1]); counts[b.body] = (counts[b.body] ?? 0) + 1
  // a percent-encoded path is also written decoded, so the rule applies whichever form the host matches against
  const dec = decodeURIComponent(p); if (dec !== p) add(dec, t[0], t[1])
}
// hosted PDFs: legacy file address -> hosted copy
const legacyFiles = new Set(csv('agent/parity/legacy-files.csv').map(r => r.url))
let files = 0
for (const r of csv('agent/parity/documents-sources.csv')) {
  const m = r.legacy_file.match(/https:\/\/\S+?\.pdf/) ?? (r.hosted_as.includes('annual-report-2021') ? ['https://www.cuahsi.org/uploads/library/doc/Annual_Report_2021_-_Visual.pdf'] : null)
  if (!m || !legacyFiles.has(m[0])) throw new Error('no legacy file for ' + r.title)
  add(path(m[0]), r.hosted_as, 'hosted PDF'); files++
}
const lines = ['# Generated by scripts/parity/redirects.mjs. Legacy www.cuahsi.org paths for bodies of work that now exist here.', '# One rule per line: source, target, status. Do not edit by hand; change the script and run it again.']
let last = ''
for (const [from, [to, why]] of [...rules].sort((a, b) => a[1][1].localeCompare(b[1][1]) || a[0].localeCompare(b[0]))) {
  if (why !== last) { lines.push('', '# ' + why); last = why }
  lines.push(`${from} ${to} 301`)
}
// A rewrite, not a redirect: /flooding-gages.json is served from the `flood-data` branch, which .github/workflows/flood-snapshot.yml
// refreshes every 3 hours (the home page's gage card reads it). Netlify fetches it server side, so visitors only talk to this site.
// The repository is the one the workflow runs in; change it here if production builds from another repository.
const FLOOD_DATA = 'https://raw.githubusercontent.com/jordansread/CUAHSI3-website/flood-data/flooding-gages.json'
lines.push('', '# the NWS flood snapshot (a rewrite), refreshed by .github/workflows/flood-snapshot.yml', `/flooding-gages.json ${FLOOD_DATA} 200`)
const out = lines.join('\n') + '\n'
if (process.argv.includes('--check')) {
  const have = fs.existsSync('public/_redirects') ? fs.readFileSync('public/_redirects', 'utf8') : ''
  if (have !== out) { console.log('public/_redirects differs from what scripts/parity/redirects.mjs produces; run it and commit the result'); process.exit(1) }
  console.log(`redirect file matches its generator (${rules.size} rules)`)
} else {
  fs.writeFileSync('public/_redirects', out)
  console.log(rules.size, 'redirects;', JSON.stringify(counts), files, 'hosted PDFs;', held, 'library pages held back')
}
